[profile.default]
solc = "0.8.28"
src = "src"
out = "out"
evm_version = 'cancun'
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
